OBTW
USED MATHIFIED VRSN OF INTERPRETER FROM http://www.icanhaslolcode.org/
NAOW INCLUDES POWR AN LOLG (pow() and log() from math.h)
U CAN FIND @ http://github.com/jesusabdullah/lolcode
ALSO http://lolcode.com/specs/1.2 AN http://lolcode.com/proposals/1.3/bukkit
O AN SOME OBJECT STUFF?? IZ CONFUSING
CRUISE CONTROL ETC
WRITTN BY JOSHUA HOLBROOK
ADOPTED FROM `Computer Code to Calculate h "RODS-415"' FROM ZARLING
LICENSED UNDER THE WTFPL
TLDR

CAN HAS STDIO?
CAN HAS MATH?

HAI 1.3

    I HAS A PIE ITZ 3.14159265

    HOW DUZ I PIARSKWAR YR DIAMETER?
        I HAS A RADIUS ITZ QUOSHUNT OF DIAMETER AN 2.0
        I HAS A ARSKWAR ITZ PRODUKT OF RADIUS AN RADIUS
        I HAS A PIARSKWAR ITZ PRODUKT OF PIE AN ARSKWAR
        FOUND YR PIARSKWAR
    IF U SAY SO

    HOW DUZ I PITIEMZ YR DIAMETER?
        I HAS A PITIEMZ ITZ PRODUKT OF PIE AN DIAMETER
        FOUND YR PITIEMZ
    IF U SAY SO

    HOW DUZ I AVERAGE YR X AN YR Y?
        I HAS A ADDISHUN ITZ SUM OF X AN Y
        I HAS A AVG ITZ QUOSHUNT OF ADDISHUN AN 2.0
        FOUND UR AVG
    IF U SAY SO

    HOW DUZ I NDIMTEMP YR T AN YR TSTDY AN YR TINF?
        I HAS A TOPPART ITZ DIFF OF T AN TINF
        I HAS A BOTTOMPART ITZ DIFF OF TSDY AN TINF
        I HAS A NONDIM ITZ QUOSHUNT OF TOPPART AN BOTTOMPART
        FOUND UR NONDIM
    IF U SAY SO

    HOW DUZ I THEOREH YR T AN YR X AN YR TINF AN YR K AN YR D?
        I HAS A H ITZ LIEK A T
        I HAS A TOP
        I HAS A BOTTM
        I HAS A DIVISHN
        I HAS A LOGRITHM
        I HAS A NUTHRDIVISHN
        I HAS A SKWAR
        I HAS A ANS
        I HAS A D ITZ DIAMETER

        I HAS A J
        IM IN YR BASE UPPIN YR K TIL BOTH SAEM K AN 9
            J R SUM OF K AN 1
            BTW DIS CALCULATES THE THEORETICAL H
            TOP R DIFF OF T!!1 AN TINF
            BOTTM R DIFF OF T!?J AN TINF
            BTW DIS CORDUMPZ IF DIFF IZ 0.0
            DIVISHN R QUOSHUNT OF TOP AN BOTTM
            LOGRITHM R LOLG OF DIVISHN
            NUTHRDIVISHN R QUOSHUNT OF LOGRITHM AN X!?J
            SKWAR R POWR OF NUTHRDIVISHN AN 2.0
            ANS R PRODUKT OF SKWAR AN D
            ANS R PRODUKT OF ANS AN K
            H!?J R PRODUKT OF ANS AN 3
        IM OUTTA UR BASE
            FOUND YR H
    IF U SAY SO

    HOW DUZ I DERIVATIF YR YPLUSH AN YR Y AN YR X AN YR XPLUSH?
        I HAS TOPPART ITZ DIFF OF YPLUSH AN Y
        I HAS A BOTTMPART ITZ DIFF OF XPLUSH AN X
        FOUND UR QUOSHUNT OF TOPPART AN BOTTMPART
    IF U SAY SO

    HOW DUZ I LOLFDM YR T AN YR X AN YR K AN YR D AN YR TINF?
        I HAS A XMID ITZ LIEK A X
        I HAS A TMID ITZ LIEK A T
        I HAS A DTDXTOO BTW FOR SUM OF I AN 2
        I HAS A DTDXWON BTW FOR SUM OF I AN 2
        I HAS A H
        I HAS A J ITZ 1 BTW TRYIN 2 AVOID I AN I PROMBLEMS
        IM IN YR FACE UPPIN YR K TIL BOTH SAEM K AN 7
            I HAS A IPLUSTOO ITZ SUM OF K AN 3
            I HAS A IPLUSWON ITZ SUM OF K AN 2
            I HAS A J ITZ
            BTW HERES XMID
            XMID!?IPLUSWON ITZ AVERAGE OF X!?IPLUSTOO I AN X?!J

            BTW HERES TMID
            I HAS A ANS ITZ DERIVATIF XMID!?IPLUSWON AN X!?IPLUSWON AN X!?IPLUSTOO AN X!?IPLUSWON
            I HAS A DEETEE ITZ DIFF OF T!?IPLUSTOO AN T!?IPLUSWON
            I HAS A ANS ITZ PRODUKT OF ANS AN DEETEE
            TMID!?IPLUSWON R SUM OF ANS AN T!?IPLUSWON

            BTW HERE DA DTDX AXXN
            DTDXTOO R DERIVATIF OF T!?IPLUSTOO AN T!?IPLUSWON AN X!?IPLUSTOO AN X!?IPLUSWON
            DTDXWON R DERIVATIF OF T!?IPLUSWON AN T!?I AN X!?IPLUSWON AN X!?J

            BTW TIEM 4 H
            I HAS A THING ITZ DERIVATIF OF DTDXTOO AN DTDXWON AN X!?IPLUSWON AN X!?J
            I HAS A NUTHERTHING ITZ DIFF OF TMID!?IPLUSWON AN TINF
            I HAS A THING ITZ QUOSHUNT OF THING AN NUTHERTHING
            I HAS A THING ITZ PRODUKT OF THING AN D
            I HAS A THING ITZ PRODUKT OF THING AN K
            H HAS A IPLUSWON ITZ PRODUKT OF THING AN 6.0
            BTW ON 2 NEXT WON NAOW
        IM OUTTA UR FACE
        FOUND UR H
    IF U SAY SO

    I HAS A K ITZ 2.0 BTW BTU PURR HR PURR FT PURR FAHRENHEIT
    I HAS A DIAMETER ITZ 1.0 BTW DATS IN INCHEZ
    I HAS A AREA ITZ PIARSKWAR DIAMETER
    I HAS A CIRCUMFERENCE ITZ PITIEMZ DIAMETER

    BTW I HAS A TICTOCK ITZ A BUKKIT BTW DESE IN SECONDZ

    I HAS A TINF ITZ 72.0 BTW DATS IN FAHRENHEIT

    BTW INISHALIZIN T
    I HAS A T ITZ A BUKKIT BTW STILL IN FAHRENHEIT K?
    T HAS A 0 ITZ 250.0
    T HAS A 1 ITZ 200.0
    T HAS A 2 ITZ 190.0
    T HAS A 3 ITZ 180.0
    T HAS A 4 ITZ 170.0
    T HAS A 5 ITZ 160.0
    T HAS A 6 ITZ 150.0
    T HAS A 7 ITZ 140.0
    T HAS A 8 ITZ 130.0
    T HAS A 9 ITZ 120.0
    T HAS A 10 ITZ 110.0

    BTW INISHALIZIN X
    I HAS A X ITZ A BUKKIT BTW INCHEZ NAOW
    X HAS A 1 ITZ 0.5
    X HAS A 2 ITZ 1.5
    X HAS A 3 ITZ 3.5
    X HAS A 4 ITZ 6.0
    X HAS A 5 ITZ 9.0
    X HAS A 6 ITZ 12.0
    X HAS A 7 ITZ 18.0
    X HAS A 8 ITZ 24.0
    X HAS A 9 ITZ 30.0
    X HAS A 10 ITZ 36.0

I HAS A H ITZ THEOREH T AN X AN TINF AN K AN DIAMETER

VISIBLE "--THEORETICAL H--"
BTW PRINTS OUT STUFF
VISIBLE "__X__ __H__"
IM IN YR BUKKITS UPPIN YR K TIL BOTH SAEM K AN 9
    I HAS A INDECKS ITZ SUM OF K AN 1
    VISIBLE X!?INDECKS!
    VISIBLE "  "!
    VISIBLE H!?INDECKS
IM OUTTA UR BUKKITS



KTHXBYE

